image_name_base: optuna-batch
instance_name: optuna-batch
bucket_name: optuna-batch
project_id: your-project-id
region: asia-northeast1
zone: asia-northeast1-a
repository: repository
service_account: optuna-batch@your-project-id.iam.gserviceaccount.com

n_trials: 100
n_jobs: 3

compute_resorce:
  cpu_milli: 1
  memory_mib: 128
allocation_policy:
  machine_type: e2-micro
  provisioning_model: "SPOT"